### ISSUE TITLE
Improve cpp0337 and cpp0336 code

### ISSUE THREAD

**Issue by vucongtuanduong** [NNT1208PT173/Code.ptit_cpp#1]
We can use `map` data structure instead of frequency array and use `INT_MAX` instead of a very big number in `min` variable. This is my improved code based on your algorithm. 

`Link: https://github.com/vucongtuanduong/cpp-codeptit/blob/main/string/basic/cpp0337/cpp0337.cpp`
Same with cpp0336

**Comment by yalza** [comment]
thanks b nhé !
